@startuml Example of Event Pattern
set separator none
hide empty members

package padlock.h {
    class padlock_t {
        -key
        -entry
        -penalty
        -OnError()
        -OnSuccess()
        +Create()
        +Tick()
        +SetPenalty()
    }
    interface padlock_event_t {
    }
    padlock_t o-d- padlock_event_t
}

package main.c {
   protocol onSuccess {
   }
   onSuccess .u.|> padlock_event_t

   protocol onError {
   }
   onError .u.|> padlock_event_t
}
@enduml
